services:
  - type: web
    name: quran-academy-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL_HERE
